
version: 2

models:
  - name: stg_superheroes
    description: Demographics about each superhero such as name, hair color, height and weight. 
    columns:
      - name: name
        tests:
          - not_null
      - name: height
        tests:
          - positive_values
      - name: weight
        tests:
          - positive_value
  - name: stg_promos
    description: promotion information. discounts are positive values 
    columns:
      - name: discount
        tests:
         - positive_value
  - name: stg_products
    description: product descriptions
    columns:
      - name: price
        tests:
          - positive_values
      - name: quantity
        tests:
          - positive_value
