version: 2

models: 
  - name: dim_users
    description: "Users dimension table ... "
    columns:
      - name: user_id
        description: "This is the user unique id for the table"
        tests:
          - unique
          - not_null
  - name: dim_orders
  - name: orders_per_user
  - name: repeat_rate 
macros: 
  - name: get_page_part
    arguments:
    - name: page_url
      type: string

exposures:  
  - name: fact_event_rates
    description: >
      Models that provide metrics for funnel
    type: dashboard
    maturity: high
    owner:
      name: Tony Nickel
      email: janickel@ucsc.edu
    depends_on:
      - ref('stg_events')
      - ref('session_events')
      - ref('fact_event_rates')